Fixed cleanup method call in hiredis spec
The previous call to #delete was actually raising an error, because the
method name is #del. Unless you had previously set the "key" key, the
test would have passed. Setting it to a string would expose the
following error:

     NoMethodError:
            undefined method `to_i' for #<RuntimeError:0x007fd4e1842660>

Fixed by using the right cleanup method. Does anyone know why the bad
call to #delete didn't raise an error?